repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.4.3
  hooks:
    # Run the linter.
    - id: ruff
    # Run the formatter.
    - id: ruff-format

- repo: local
  hooks:
    - id: update-api-schema
      name: Update API Schema
      entry: bash -c 'if command -v python >/dev/null 2>&1; then make build-apischema || echo "⚠️  Could not update API schema - make sure Django dependencies are installed"; fi'
      language: system
      files: '^polarrouteserver/route_api/views\.py$'
      pass_filenames: false
      stages: [pre-commit]
