# Generated by Django 5.0.7 on 2024-08-02 09:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mesh",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("requested", models.DateTimeField(default=django.utils.timezone.now)),
                ("calculated", models.DateTimeField(null=True)),
                ("file", models.FilePathField(blank=True, null=True)),
                ("status", models.TextField(null=True)),
                ("meshiphi_version", models.CharField(max_length=60, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("requested", models.DateTimeField(default=django.utils.timezone.now)),
                ("calculated", models.DateTimeField(null=True)),
                ("file", models.FilePathField(blank=True, null=True)),
                ("status", models.TextField(null=True)),
                ("start_lat", models.FloatField()),
                ("start_lon", models.FloatField()),
                ("end_lat", models.FloatField()),
                ("end_lon", models.FloatField()),
                ("json", models.JSONField(null=True)),
                ("polar_route_version", models.CharField(max_length=60, null=True)),
                (
                    "mesh",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="route_api.mesh",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("datetime", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="route_api.route",
                    ),
                ),
            ],
        ),
    ]
