# Generated by Django 5.0.6 on 2024-05-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("route_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mesh",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="route",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
