# Generated by Django 5.0.7 on 2024-09-10 20:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("route_api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mesh",
            old_name="status",
            new_name="info",
        ),
        migrations.RenameField(
            model_name="route",
            old_name="status",
            new_name="info",
        ),
    ]
