# Generated by Django 5.1.1 on 2024-10-15 17:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("route_api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mesh",
            name="calculated",
        ),
        migrations.RemoveField(
            model_name="mesh",
            name="file",
        ),
        migrations.RemoveField(
            model_name="mesh",
            name="requested",
        ),
        migrations.RemoveField(
            model_name="mesh",
            name="status",
        ),
        migrations.AddField(
            model_name="mesh",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mesh",
            name="json",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="mesh",
            name="lat_max",
            field=models.FloatField(default=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mesh",
            name="lat_min",
            field=models.FloatField(default=-90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mesh",
            name="lon_max",
            field=models.FloatField(default=180),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mesh",
            name="lon_min",
            field=models.FloatField(default=-180),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mesh",
            name="md5",
            field=models.CharField(default="", max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="route",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
