# Generated by Django 5.0.6 on 2024-05-08 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("route_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("datetime", models.DateTimeField()),
                ("status", models.TextField(null=True)),
                (
                    "mesh",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="route_api.mesh",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="route_api.route",
                    ),
                ),
            ],
        ),
    ]
