# Generated by Django 5.1.1 on 2024-10-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("route_api", "0002_remove_mesh_calculated_remove_mesh_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mesh",
            name="name",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
