# Generated by Django 5.0.6 on 2024-07-04 14:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("route_api", "0002_alter_mesh_id_alter_route_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="datetime",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
