# Generated by Django 5.0.6 on 2024-07-10 15:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("route_api", "0003_alter_job_datetime"),
    ]

    operations = [
        migrations.RenameField(
            model_name="route",
            old_name="waypoint_end_lat",
            new_name="end_lat",
        ),
        migrations.RenameField(
            model_name="route",
            old_name="waypoint_end_lon",
            new_name="end_lon",
        ),
        migrations.RenameField(
            model_name="route",
            old_name="waypoint_start_lat",
            new_name="start_lat",
        ),
        migrations.RenameField(
            model_name="route",
            old_name="waypoint_start_lon",
            new_name="start_lon",
        ),
    ]
