# Generated by Django 5.0.6 on 2024-07-22 15:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("route_api", "0004_rename_waypoint_end_lat_route_end_lat_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="status",
        ),
        migrations.AddField(
            model_name="route",
            name="json",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="mesh",
            name="requested",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="route",
            name="requested",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
