# Generated by Django 5.0.7 on 2024-07-24 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("route_api", "0006_mesh_meshiphi_version_route_polar_route_version"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="mesh",
        ),
        migrations.RemoveField(
            model_name="job",
            name="route",
        ),
        migrations.AddField(
            model_name="mesh",
            name="job",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="route_api.job",
            ),
        ),
        migrations.AddField(
            model_name="route",
            name="job",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="route_api.job",
            ),
        ),
    ]
