# Generated by Django 5.1.1 on 2024-10-17 14:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mesh",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("meshiphi_version", models.CharField(max_length=60, null=True)),
                ("md5", models.CharField(max_length=64)),
                ("created", models.DateTimeField()),
                ("lat_min", models.FloatField()),
                ("lat_max", models.FloatField()),
                ("lon_min", models.FloatField()),
                ("lon_max", models.FloatField()),
                ("json", models.JSONField(null=True)),
                ("name", models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requested", models.DateTimeField(default=django.utils.timezone.now)),
                ("calculated", models.DateTimeField(null=True)),
                ("file", models.FilePathField(blank=True, null=True)),
                ("info", models.TextField(null=True)),
                ("start_lat", models.FloatField()),
                ("start_lon", models.FloatField()),
                ("end_lat", models.FloatField()),
                ("end_lon", models.FloatField()),
                ("json", models.JSONField(null=True)),
                ("json_unsmoothed", models.JSONField(null=True)),
                ("polar_route_version", models.CharField(max_length=60, null=True)),
                (
                    "mesh",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="route_api.mesh",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("datetime", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="route_api.route",
                    ),
                ),
            ],
        ),
    ]
