# Generated by Django 5.1.1 on 2024-11-07 21:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("route_api", "0003_route_end_name_route_start_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="route",
            name="file",
        ),
    ]
