# Generated by Django 5.1.1 on 2024-11-07 21:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("route_api", "0004_remove_route_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="route",
            name="end_name",
            field=models.CharField(blank=True, default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="route",
            name="start_name",
            field=models.CharField(blank=True, default=None, max_length=100),
            preserve_default=False,
        ),
    ]
