# Generated by Django 5.1.1 on 2024-11-19 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("route_api", "0008_mesh_valid_date_end_mesh_valid_date_start"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="route",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="route_api.route",
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="mesh",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="route_api.mesh",
            ),
        ),
    ]
