# Generated by Django 5.1.1 on 2024-11-26 14:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("route_api", "0009_alter_job_route_alter_route_mesh"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mesh",
            options={"verbose_name_plural": "Meshes"},
        ),
    ]
