# Generated by Django 5.2.1 on 2025-06-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("route_api", "0011_alter_mesh_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "vessel_type",
                    models.CharField(
                        default=None,
                        max_length=150,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("max_speed", models.FloatField()),
                ("unit", models.CharField(max_length=150)),
                ("max_ice_conc", models.FloatField(null=True)),
                ("min_depth", models.FloatField(null=True)),
                ("max_wave", models.FloatField(null=True)),
                ("excluded_zones", models.JSONField(null=True)),
                ("neighbour_splitting", models.BooleanField(null=True)),
                ("beam", models.FloatField(null=True)),
                ("hull_type", models.CharField(max_length=150, null=True)),
                ("force_limit", models.FloatField(null=True)),
                ("created", models.DateTimeField(null=True)),
                ("created_by", models.CharField(max_length=150, null=True)),
            ],
        ),
    ]
