# Generated by Django 5.1.5 on 2025-01-23 14:43

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route_api', '0011_alter_mesh_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesh',
            name='_geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
    ]
