# Generated by Django 5.1.5 on 2025-09-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("route_api", "0012_vehicle"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lat", models.FloatField()),
                ("lon", models.FloatField()),
                ("name", models.CharField(max_length=100)),
            ],
        ),
    ]
