# Generated by Django 5.2.9 on 2025-12-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("route_api", "0016_alter_location_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="tag",
            field=models.CharField(
                blank=True,
                help_text="Optional tag for route",
                max_length=100,
                null=True,
            ),
        ),
    ]
