# Generated by Django 5.2.9 on 2025-12-03 13:31

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route_api', '0016_alter_location_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesh',
            name='geometry',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
    ]
