# Generated by Django 5.1.5 on 2025-11-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("route_api", "0016_alter_location_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
