# Generated by Django 5.2.9 on 2025-12-16 15:15

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route_api', '0017_mesh_geometry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesh',
            name='geometry',
        ),
        migrations.CreateModel(
            name='MeshPolygon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('properties', models.JSONField()),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=3857)),
                ('mesh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route_api.mesh')),
            ],
            options={
                'indexes': [models.Index(fields=['mesh'], name='route_api_m_mesh_id_80e8f5_idx')],
            },
        ),
    ]
